const workspacememberrouter=require('express').Router({ mergeParams: true });
const workspaceMemberController=require('../controllers/workspacemember.controller');
const {authMiddleware}=require('../middleware/auth.middleware');
const validate=require('../middleware/validate.middleware');
const {updateWorkspaceMemberRoleSchema}=require('../validators/workspacemember.validator');
workspacememberrouter.get('/',authMiddleware,workspaceMemberController.getWorkspaceMembers);
workspacememberrouter.delete('/:memberId',authMiddleware,workspaceMemberController.removeWorkspaceMember);
workspacememberrouter.delete('/exit',authMiddleware,workspaceMemberController.exitWorkspace);
workspacememberrouter.patch('/updaterole',authMiddleware,validate(updateWorkspaceMemberRoleSchema),workspaceMemberController.updateWorkspaceMemberRole);
module.exports=workspacememberrouter;